---
title: "Connecting to a FixelDB Demo"
output: html_notebook
---


```{r}
library(tidyverse)
library(RMariaDB)
library(RMySQL)
library(DBI)
library(tictoc)
library(parallel)
```


```{r}
con <- DBI::dbConnect(RMySQL::MySQL(),
  host = "127.0.0.1",
  user = "fixeluser",
  password = "fixels",
  port=3306,
  dbname="fixeldb"
)
```

```{r}
voxels <- tbl(con, "voxels")
voxels
```

Well that works.

```{r}
phenotypes <- tbl(con, "phenotypes")
phenotypes
```

```{r}
res = dbGetQuery(con, "SELECT * FROM FD A INNER JOIN phenotypes B ON A._id = B._id WHERE A.fixel_id = 1;")
res
```

That works too.

```{r}
n_id <- dbGetQuery(con, "SELECT MAX(fixel_id) FROM FD;") %>%
  as.integer()


```

```{r}
results <- data.frame()

tic.clearlog()
for (x in 1:n_id){
  tic(x)
  res = dbGetQuery(con, sprintf("SELECT * FROM FD A INNER JOIN phenotypes B ON A._id = B._id WHERE A.fixel_id = %d", x))
  print(x)
  results <- with(res, t.test(value ~ Diagnosis)) %>% 
    broom::tidy() %>%
    bind_rows(results, .)
  toc(log = TRUE, quiet = TRUE)
}

results <- results %>%
  mutate(time = unlist(lapply(log.lst, function(x) x$toc - x$tic)))

tic.clearlog()
```

```{r}
assert_returns_row <- function(f){
  
  # asserts that the function the user passes will return a row
  
}
```

```{r}
myfunc <- function(id){
  
  query <- sprintf("SELECT * FROM FD A INNER JOIN phenotypes B ON A._id = B._id WHERE A.fixel_id = %d", id)
  print(query)
  
  mtcars %>%
    slice(-id) %>%
    summarise_all(c(mean)) %>%
    return()

}
```

```{r}
tic()
result <- map_dfr(1:10, myfunc)
toc()
```

```{r}
tic()
result <- future_map_dfr(1:10, myfunc)
toc()
```

```{r}
myfunc2 <- function(id){
  
  t0 <- Sys.time()
  
  tryCatch({
    res = dbGetQuery(con, sprintf("SELECT * FROM FD A INNER JOIN phenotypes B ON A._id = B._id WHERE A.fixel_id = %d", id))
    if(nrow(res) < 1){
      stop(sprintf("No rows returned in query: fixel_id = %d", id))
    }
    results <- with(res, t.test(value ~ Diagnosis)) %>% 
      broom::tidy()    
    }, 
    error=function(error_message) {
        message(error_message)
        results = data.frame(time = NA)
    }
  )
  
  t1 <- Sys.time()
  
  results %>%
    mutate(time = as.double(difftime(t1, t0, units = 'secs'))) %>%
    return()

}

# plan(multiprocess)
# future_map_dfr(1:20, myfunc2)
```

```{r}
library(furrr)
plan(multiprocess)
tic()
future_map_dfr(1:10, myfunc2)
toc()

```

```{r}
library(parallelMap)
tic()
parallelStart()
f = function(i) i + 5
y = parallelMap(myfunc2, 1:20)
parallelStop()
toc()

```

```{r}
library(parallel)

numCores <- detectCores()
numCores

tic()
results <- mclapply(1:10000, myfunc2, mc.cores = numCores)
do.call(rbind, results)
toc()

```

```{r}
summary_func <- function(df){
  
  t0 <- Sys.time()
  
  out<-with(df, (t.test(value ~ Diagnosis))) %>% 
    broom::tidy()
  
  t1 <- Sys.time()
  
  out %>%
    mutate(time = as.double(difftime(t1, t0, units = 'secs'))) %>%
    return()

}

batch_function <- function(id_vec, func){
  
  for(id_num in id_vec){
    
    tryCatch({
    
      query_res = dbGetQuery(con, sprintf("SELECT * FROM FD A INNER JOIN phenotypes B ON A._id = B._id WHERE A.fixel_id = %d", id_num))
      if(nrow(res) < 1){
        stop(sprintf("No rows returned in query: fixel_id = %d", id))
      }
      
      results <- summary_func(query_res)
      
    },
    error=function(error_message) {
        message(error_message)
        results = data.frame(time = NA)
    })
  }
}

myfunc3 <- function(n_fixels, c_cores){
  
  t0 <- Sys.time()
  
  job_assignments <- tibble(n_fixels = 1:n_fixels, core = sort(1:n_fixels%%n_cores))
  
  job_assignments %>%
    group_by(core) %>%
    nest() %>%
    mutate(result = summary_func(data))
  
  tryCatch({
    res = dbGetQuery(con, sprintf("SELECT * FROM FD A INNER JOIN phenotypes B ON A._id = B._id WHERE A.fixel_id = %d", id))
    if(nrow(res) < 1){
      stop(sprintf("No rows returned in query: fixel_id = %d", id))
    }
    
    
    results <- with(res, t.test(value ~ Diagnosis)) %>% 
      broom::tidy()    
    }, 
    error=function(error_message) {
        message(error_message)
        results = data.frame(time = NA)
    }
  )
  
  t1 <- Sys.time()
  
  results %>%
    mutate(time = as.double(difftime(t1, t0, units = 'secs'))) %>%
    return()

}

# plan(multiprocess)
# future_map_dfr(1:20, myfunc2)
```

---

# A function to establish the connection

```{r}
setup_connection <- function(n){

  con <- dbConnect(MySQL(max.con = n), host = "127.0.0.1", user = "fixeluser", password = "fixels", port=3306, dbname="fixeldb")

  return(con)
}

remove_connections <- function(){
  
  lapply( dbListConnections( dbDriver( drv = "MySQL")), dbDisconnect)

}
```

# A function to establish the number of fixels available

```{r}
num_fixels <- function(connection){
  dbGetQuery(connection, "SELECT MAX(fixel_id) FROM FD;") %>%
    as.integer() + 1%>%
    return()
}
```

# A function to fetch Fixel data:

```{r}
fetch_fixel_df <- function(fixel_id, variable, connection){
  
  tryCatch(
    # try this
    {
    
    # pre-checks
    if(!is.numeric(fixel_id)){
      stop()
    }
      
    if(!is.character(variable)){
      stop()
    }
    
    # run query
    query_res <- tryCatch(error = function(cnd) cnd, dbGetQuery(connection, sprintf("SELECT * FROM %s A INNER JOIN phenotypes B ON A._id = B._id WHERE A.fixel_id = %d", variable, fixel_id)))
    
    # ensure query was successful
    if(!is.data.frame(query_res)){
      stop(print(query_res$message))
    }
    
    if(nrow(query_res) < 1){
      stop()
    }
    
    # return
    return(query_res)
  },
  
  # if not:
  error=function(error_message) {
      #message(error_message)
      return(data.frame())
  })
}
```


# An example summary function on said data
```{r}
summary_func <- function(df){
  
  t0 <- Sys.time()
  
  out<-with(df, (t.test(value ~ Diagnosis))) %>% 
    broom::tidy()
  
  t1 <- Sys.time()
  
  out %>%
    mutate(time = as.double(difftime(t1, t0, units = 'secs'))) %>%
    return()

}
```

# A batch of summary functions
```{r}
batch_function <- function(id_vec, func, variable){
  
  failed = c()
  results_df <- vector("list", length = length(id_vec))
  
  multiple_socket_connection <- setup_connection(length(id_vec))
  
  for(id_num in id_vec){
    
    ix <- id_num + 1
    
    df <- fetch_fixel_df(id_num, variable, multiple_socket_connection)
    
    if(nrow(df) < 1){
      failed <- c(failed, id_num)
    } else {
      
      fixel_summary <- summary_func(df)
      
      if(!is.data.frame(fixel_summary)){
        results_df[[ix]] <- data.frame() %>%
          mutate(fixel_id = id_num)
      }
        
      results_df[[ix]] <- fixel_summary %>%
        mutate(fixel_id = id_num)
    }
  }
  
  dbDisconnect(multiple_socket_connection)
  rm(multiple_socket_connection)
  
  print(failed)
  return(do.call(bind_rows, results_df))
  
}
```

# A function to split a fixel based analysis into batches and run in parallel

```{r}
library(parallel)
library(MASS)

starts <- rep(50000, 40)
fx <- function(nstart) kmeans(Boston, 4, nstart=nstart)
numCores <- detectCores()
numCores

tic()
results <- mclapply(starts, fx, mc.cores = numCores)
toc()
```

```{r}
library(parallel)

numCores <- detectCores() - 6
numCores

parallel_FBA <- function(id_vec, func, variable, numCores){
  
  tic()
  tibble(id_vec, core = sort(id_vec %% numCores) + 1) %>%
    group_by(core) %>%
    nest() %>%
    mutate(
      results = lapply(data, function(x){
      
        batch_function(x$id_vec, summary_func, "FD")
      
      })#, mc.cores = numCores)
    ) %>%
    unnest(results)
  toc()
}
```

```{r}
times <- list()

vecs <- c(10, 50, 100, 250, 500, 1000, 1500, 2000, 5000, 7500, 10000, 25000, 50000, 100000, 250000)

numCores <- 12

for(i in vecs){

  id_vec = 1:i
  
  t0 <- Sys.time()  
  fixel_analysis <- tibble(id_vec, core = sort(id_vec %% numCores) + 1) %>%
    group_by(core) %>%
    nest() %>%
    mutate(
      results = lapply(data, function(x){
      
        batch_function(x$id_vec, summary_func, "FD")
      
      })#, mc.cores = numCores)
    ) %>%
    unnest(results)
  t1 <- Sys.time()
  lapp_time <- as.numeric(difftime(as.POSIXct(t1), as.POSIXct(t0)))

  t0 <- Sys.time()  
  fixel_analysis <- tibble(id_vec, core = sort(id_vec %% numCores) + 1) %>%
    group_by(core) %>%
    nest() %>%
    mutate(
      results = mclapply(data, function(x){
      
        batch_function(x$id_vec, summary_func, "FD")
      
      }, mc.cores = numCores)
    ) %>%
    unnest(results)
  t1 <- Sys.time()
  mclapp_time <- as.numeric(difftime(as.POSIXct(t1), as.POSIXct(t0)))
  
  times[[i]] <- data.frame("lapp"=lapp_time, "mclapp" = mclapp_time, "n_fixels"=i)
}

bind_rows(times) %>%
  gather('method', 'seconds', -n_fixels) %>%
  ggplot(aes(x=n_fixels, y=seconds))+
    geom_line(aes(colour=method))
```

